spring:
  datasource:
    password: 3110
    url: jdbc:mysql://localhost:3306/serverdb
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  security:
    user:
      name: admin
      password: admin






